In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\voidc\onedrive\documents\github\year-2-artificial-intelligence\session3\myenv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\voidc\onedrive\documents\github\year-2-artificial-intelligence\session3\myenv\lib\site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\voidc\onedrive\documents\github\year-2-artificial-intelligence\session3\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\voidc\onedrive\documents\github\year-2-artificial-intelligence\session3\myenv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\voidc\onedrive\documents\github\year-2-artificial-intelligence\session3\myenv\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\voidc\onedrive\documents\github\year-2-artificial-intelligence\session3\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('healthcare-dataset-stroke-data.csv')

In [5]:
df.drop(["ever_married"], axis=1, inplace=True)
df.drop(["work_type"], axis=1, inplace=True)
df.drop(["Residence_type"], axis=1, inplace=True)
df.drop(["id"], axis=1, inplace=True)
df.drop(["avg_glucose_level"], axis=1, inplace=True)
df.drop(["bmi"], axis=1, inplace=True)

In [6]:
df.sample(7)

      gender    age  hypertension  heart_disease   smoking_status  stroke
894     Male  81.00             1              0  formerly smoked       0
58      Male  73.00             1              0     never smoked       1
2601  Female  79.00             0              0  formerly smoked       0
1314    Male  45.00             0              0     never smoked       0
4000  Female  24.00             0              0     never smoked       0
2614  Female  58.00             0              0  formerly smoked       0
3618    Male   0.16             0              0          Unknown       0

In [7]:
df.groupby([ "gender","age","hypertension", "heart_disease", "smoking_status"])["stroke"].agg({"mean"})

                                                         mean
gender age   hypertension heart_disease smoking_status
Female 0.08  0            0             Unknown           0.0
       0.32  0            0             Unknown           0.0
       0.40  0            0             Unknown           0.0
       0.48  0            0             Unknown           0.0
       0.56  0            0             Unknown           0.0
...                                                       ...
Male   82.00 0            1             formerly smoked   0.0
                                        never smoked      0.5
                                        smokes            1.0
             1            0             never smoked      0.0
Other  26.00 0            0             formerly smoked   0.0

[1061 rows x 1 columns]

In [8]:
df.groupby(["hypertension", "heart_disease"])["stroke"].agg({"mean"})

                                mean
hypertension heart_disease
0            0              0.033864
             1              0.160377
1            0              0.122120
             1              0.203125

In [9]:
grouped = df.groupby(["age", "hypertension", "heart_disease"])

specific = grouped.get_group((82, 1, 1))
print(specific)

mean = grouped["stroke"].mean()
print(mean)

a = 1

mean_grouped = mean.loc[(82, a, 1)]
print(mean_grouped)

      gender   age  hypertension  heart_disease   smoking_status  stroke
35    Female  82.0             1              1  formerly smoked       1
187   Female  82.0             1              1  formerly smoked       1
3400  Female  82.0             1              1     never smoked       0
4590  Female  82.0             1              1     never smoked       0
age    hypertension  heart_disease
0.08   0             0                0.000000
0.16   0             0                0.000000
0.24   0             0                0.000000
0.32   0             0                0.000000
0.40   0             0                0.000000
                                        ...
81.00  1             1                0.166667
82.00  0             0                0.090909
                     1                0.300000
       1             0                0.111111
                     1                0.500000
Name: stroke, Length: 233, dtype: float64
0.5

In [ ]:
# Function to predict the chance of stroke based on inputted values
def chance_of_stroke(gender, age, hypertension, heart_disease, smoking):
    # Format got from chatgpt 
    
    # High risk if Female and over the age of 65 etc
    if gender == "Female" and age > 65:
        return "High risk"
    if smoking == "smokes":
        return "high risk"
    if hypertension == "1":
        return "high risk"
    if heart_disease == "1":
        return "high risk"
    
    if smoking == "formerly smoked":
        return "moderate risk"
    if age >= 45:
        return "moderate risk"
    
    # default risk level if other conditions don't match
    return "low risk"

# collecting the user inputs 
gender1 = input("What is your gender?")
# standardizing the gender input to match the function
if gender1 == "female" or gender1 == "Female":
    gender1 = "Female"
else: gender1 = "Male"

age1 = int(input("What is your current age?"))

hypertension1 = input("Do you suffer from hypertension?")
if hypertension1 == "Yes" or hypertension1 == "yes" or hypertension1 == "1" :
    hypertension1 = "1"
    hypertension2 = 1
else: 
    hypertension1 = "0" 
    hypertension2 = 0

heart_disease1 = input("Do you suffer from heart disease?")
if heart_disease1 == "Yes" or heart_disease1 == "yes" or hypertension1 == "1":
    heart_disease1 = "1"
    heart_disease2 = 1
else: 
    heart_disease1 = "0"
    heart_disease2 = 0

smoking_status1 = input("Do you currently smoke (smokes) or have been a smoker in the past (former)")
if smoking_status1 == "former":
    smoking_status1 = "formerly smoked"
elif smoking_status1 == "smokes":
    smoking_status1 = "smokes"
else: 
    smoking_status1 = "never smoked"

# calling on function to predict stroke risk based on users inputs
Test = chance_of_stroke(gender=gender1, age=age1, hypertension=hypertension1, heart_disease=heart_disease1, smoking=smoking_status1)

# displaying the stroke risk
print(f"Stroke Risk: {Test}")

# filter age over 65 from chatgpt
if age1 > 65:
    df_over_65 = df[df['age'] > 65]
else: df_over_65 = df[df['age'] < 65]

# grouping together data from the dataset based on selected values
group = df_over_65.groupby(["gender", "hypertension", "heart_disease", "smoking_status"])

# calculating the mean of stroke occuring in each group
mean = group["stroke"].mean()

# mean.loc got from chatgpt 
# finds the mean stroke chance in the users group
mean_filter = (mean.loc[(gender1, hypertension2, heart_disease2, smoking_status1)]) * 100
print("Roughly",mean_filter, "percent of people with a similar status of you have experienced a stroke")

Stroke Risk: moderate risk
Roughly 1.0660980810234542 percent of people with a similar status of you have experienced a stroke

In [ ]:
# function to define whether a person is at a high risk of stroke
def high_risk_of_stroke(person):

# returns true if any of following conditions match
# has to be female and over the age of 65 to return true
    if Female(person):
        if over_65:
            return True
        
    if hypertension(person):
        return True
    
    if heart_disease(person):
        return True
    
    if smoking(person):
        return True
    
    # if none of conditions of met, return false
    return False

# What each condition is trying to match
def Female(person):
    return person["gender"] == "Female"

def over_65(person):
    return person["age"] >= 65

def hypertension(person):
    return person["hypertension"] == 1

def heart_disease(person):
    return person["heart_disease"] == 1

def smoking(person):
    return person["smoking_status"] == "smokes"

# example of participant or sample data
person = {
    "gender": "Female",
    "age": 65,
    "hypertension": 1,
    "heart_disease": 1,
    "smoking_status": "smokes"
}

# runs the function with the data of "person"
comfirmed_high_risk = high_risk_of_stroke(person)
print("high risk:", comfirmed_high_risk)

# following code only runs if high risk is confirmed
if comfirmed_high_risk == True:

    # applying the function conditions to the dataset:
    # filter the dataset for the individuals that have confirment to have had a stroke 
    df_stroke = df[df["stroke"] == 1]
    
    # Create a new column in the dataset indicating whether each individual is at high risk (chatGPT)
    df["confirmed_high_risk"] = df_stroke.apply(high_risk_of_stroke, axis=1)
    
    # calculate how many people match with at least one condition
    Total_matches = df["confirmed_high_risk"].sum()
    
    # finding the percentage of those that match the high risk criteria in the dataset
    mean_high_risk = (Total_matches / 5110) * 100
    
    # prints of the calculated percentage
    print("Percentage of datasets that meet at least 1 of the requirements to have a high risk of stroke:", mean_high_risk)

high risk: False
Percentage of datasets that meet at least 1 of the requirements to have a high risk of stroke: 4.7749510763209395